### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by magdawrz** [magdawrz/ias_project#1]
- [x] parametry (pomieszane szerokosci, dlugosci w dark sky) - sprawdzic przekazywane parametry
- [x] weather_hub - konfiguracja (przekazywanie konfiguracji)
- [x] weather_hub - test
- [x] Provider #2 + test
- [x] Provider #3 + test
- [x] dokumentacja - README.md
- [x] html z mapa
